config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events, :only => [:index, :new, :create, :show]
#  get 'events/index'
#  get 'events/new'
#  get 'events/create'
#  post '/events' => 'events#create'
#  get 'events/show'
#  get 'events/:id' => 'events#show'
  resources :tickets
  #root :to => "tickets#index"
  root :to => "static#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :tickets
    validates :artist, :presence => true, :length => { :minimum => 2 }
    validates :price_low, :presence => true, :numericality => true
    validates :price_high, :presence => true, :numericality => true
    validates :event_date, :presence => true
		validate :event_date_not_from_past
		validate :price_high_not_lower_than_price_low
    def event_date_not_from_past
		  if event_date < Date.today
				errors.add('Data wydarzenia', 'nie może być z przeszłości')
			end
		end
		def price_high_not_lower_than_price_low
			if price_high < price_low
				errors.add('Cena biletu', 'max nie może być mniejsza od low')
			end
		end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :event
    belongs_to :user
    validates :name, :presence => true, :length => { :minimum => 6 }
    validates :email_address, :presence => true, format: { with: /\A^.+@.+$\z/, message: "Nieprawidłowy adres email" }
    validates :price, :presence => true
    validates :phone, :presence => true, length: { minimum: 9, maximum: 9 }, format: { with: /\A^[0-9]+$\z/, message: "Nieprawidłowy numer telefonu" }
end

app/models/user.rb
class User < ApplicationRecord
	has_many :tickets
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]
  before_action :check_logged_in, :only => [:new, :create]
  
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

	def create
  	event_parmas = params.require(:event).permit(:artist, :description, :price_low, :price_high, :event_date)
	  @event = Event.new(event_parmas)
	  if @event.save
	    flash[:komunikat] = 'Event został poprawnie stworzony.'
	    redirect_to "/events/#{@event.id}"
	  else
	    render 'new'
	  end
	end
  
  def show
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end
    
    def check_logged_in
			authenticate_or_request_with_http_basic("Ads") do |username, password| 
					username == "admin" && password == "admin"
			end
		end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:name, :seat_id_seq, :address, :price, :email_address, :phone, :event_id, :user_id)
    end
    
    def correct_user
			@ticket = current_user.tickets.find_by(id: params[:id])
			redirect_to tickets_path, notice: "Nie jesteś uprawniony do edycji tego biletu" if @ticket.nil?
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true, url: events_path) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist %>
  </div>

  <div class="field">
    <%= form.label :price_low %>
    <%= form.text_field :price_low %>
  </div>

  <div class="field">
    <%= form.label :price_high %>
    <%= form.text_area :price_high %>
  </div>

  <div class="field">
    <%= form.label :event_date %>
    <%= form.date_select :event_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_formt.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
    <% if ticket.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

          <ul>
            <% ticket.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :seat_id_seq %>
      <%= form.text_field :seat_id_seq %>
    </div>

    <div class="field">
      <%= form.label :address %>
      <%= form.text_area :address %>
    </div>

    <div class="field">
      <%= form.label :price %>
      <%= form.text_field :price %>
    </div>

    <div class="field">
      <%= form.label :email_address %>
      <%= form.text_field :email_address %>
    </div>

    <div class="field">
      <%= form.label :phone %>
      <%= form.text_field :phone %>
    </div>

    <div class="field">
      <%= form.label :event_id %>
      <%= form.text_field :event_id %>
    </div>

    <div class="field">
      <%= form.label :user_id %>
      <%= form.text_field :user_id %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/events/_new_ticket.html.erb
<h1>Nowy bilet</h1>

<%= render 'formt', ticket: ticket %>

app/views/events/_tickets_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Bilety</h1>

<table>
  <thead>
    <tr>
      <th>Imię</th>
      <th>Siedzenie</th>
      <th>Adres</th>
      <th>Cena</th>
      <th>Email</th>
      <th>Telefon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.name %></td>
        <td><%= ticket.seat_id_seq %></td>
        <td><%= ticket.address %></td>
        <td><%= ticket.price %></td>
        <td><%= ticket.email_address %></td>
        <td><%= ticket.phone %></td>
        <td><%= link_to 'Pokaż', ticket %></td>
        <td><%= link_to 'Edytuj', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Usuń', ticket, method: :delete, data: { confirm: 'Jesteś pewien?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<h1>Wszystkie wydarzenia</h1>
<ul>
  <% for event in @events %>
		<li><%= link_to event.artist, event %></li>
  <% end %>
</ul>

<td><%= link_to 'Nowe ogłoszenie', new_event_path, class: 'btn btn-success btn-xs' %></td>

app/views/events/new.html.erb
<h1>Nowe wydarzenie</h1>

<%= render 'form', event: @event %>

<td><%= link_to 'Back', events_path, class: 'btn btn-warning btn-xs' %></td>

app/views/events/show.html.erb
<p id="komunikat"><%= flash[:komunikat] %></p>

<p>
  <strong>Artysta:</strong>
  <%= @event.artist %>
</p>

<p>
  <strong>Min cena:</strong>
  <%= @event.price_low %>
</p>

<p>
  <strong>Max cena:</strong>
  <%= @event.price_high %>
</p>

<p>
  <strong>Data:</strong>
  <%= @event.event_date %>
</p>

<%= render "tickets_list", tickets: @event.tickets %>

<%= render "new_ticket", ticket: Ticket.new(:event_id => @event.id, :user_id=>current_user.id) %>

<td><%= link_to 'Back', events_path, class: 'btn btn-warning btn-xs' %></td>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bilety</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<p class="navbar-text pull-right">
			<% if user_signed_in? %>Logged in as <strong><%= current_user.email %></strong>.
				<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
				<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'
			%>
			<% else %>
				<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %>
				<%= link_to "Login", new_user_session_path, :class => 'navbar-link'%>
			<% end %>
		</p>
		<% if notice %>
			<p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %><p class="alert alert-danger">
			<%= alert %></p>
		<% end %>
    <%= yield %>
  </body>
</html>

app/views/tickets/_events_list.html.erb
<h1>Wszystkie wydarzenia</h1>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Artist</th>
    </tr>
  </thead>
  <tbody>
    <% events.each do |event| %>
      <tr>
        <td><%= event.id %></td>
        <td><%= event.artist %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
    <% if ticket.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

          <ul>
            <% ticket.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :seat_id_seq %>
      <%= form.text_field :seat_id_seq %>
    </div>

    <div class="field">
      <%= form.label :address %>
      <%= form.text_area :address %>
    </div>

    <div class="field">
      <%= form.label :price %>
      <%= form.text_field :price %>
    </div>

    <div class="field">
      <%= form.label :email_address %>
      <%= form.text_field :email_address %>
    </div>

    <div class="field">
      <%= form.label :phone %>
      <%= form.text_field :phone %>
    </div>

    <div class="field">
      <% if ticket.event_id.nil? %>
          <%= form.label :event_id %>
          <%= form.text_field :event_id %>
      <% else %>
          <%= form.hidden_field :event_id %>
      <% end %>
    </div>

    <div class="field">
      <%= form.label :user_id %>
      <%= form.text_field :user_id %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Edycja biletu</h1>

<%= render 'form', ticket: @ticket %>

<%= render "events_list", events: Event.all %>

<td><%= link_to 'Pokaz', @ticket, class: 'btn btn-info btn-xs' %></td>
<td><%= link_to 'Powrót', tickets_path, class: 'btn btn-warning btn-xs' %></td>

app/views/tickets/index.html.erb
<h1>Bilety</h1>

<table class = "table-striped">
  <thead>
  <tr>
    <th>Nazwa</th>
    <th>Siedzenie</th>
    <th>Adre</th>
    <th>Cena</th>
    <th>Email</th>
    <th>Telefon</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.name %></td>
        <td><%= ticket.seat_id_seq %></td>
        <td><%= ticket.address %></td>
        <td><%= ticket.price %></td>
        <td><%= ticket.email_address %></td>
        <td><%= ticket.phone %></td>
        <td><%= link_to 'Pokaż', ticket, class: 'btn btn-info btn-xs' %></td>
        <% if ticket.user == current_user %>
            <td><%= link_to  edit_ticket_path(ticket), class: 'btn btn-info btn-xs' do %>
                  <i class="glyphicon glyphicon-pencil"></i> Edit
              <% end %>
            </td>
            <td><%= link_to  ticket, class: 'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Jesteś pewien?' }  do %>
                  <i class="glyphicon glyphicon-remove"></i> Destroy
              <% end %>
            </td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<td><%= link_to 'Kup bilet', new_ticket_path, class: 'btn btn-success btn-xs' %></td>

app/views/tickets/new.html.erb
<h1>Kupno nowego biletu</h1>

<%= render 'form', ticket: Ticket.new( :user_id=>current_user.id) %>

<%= render "events_list", events: Event.all %>

<td><%= link_to 'Powrót', tickets_path, class: 'btn btn-warning btn-xs' %></td>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nazwa:</strong>
  <%= @ticket.name %>
</p>

<p>
  <strong>Numer siedzenia:</strong>
  <%= @ticket.seat_id_seq %>
</p>

<p>
  <strong>Adres:</strong>
  <%= @ticket.address %>
</p>

<p>
  <strong>Cena:</strong>
  <%= @ticket.price %>
</p>

<p>
  <strong>Email:</strong>
  <%= @ticket.email_address %>
</p>

<p>
  <strong>Numer telefonu:</strong>
  <%= @ticket.phone %>
</p>

<% if @ticket.user == current_user %>
	<%= link_to 'Edytuj', edit_ticket_path(@ticket) %> |
<% end %>

<%= link_to 'Wróć', tickets_path %>